<a href="https://colab.research.google.com/github/Nramyanaga/Pytorch-Learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors
A torch is a multi deimensional matrix containing elements of a sing data type
similiar to numpy arrays, but full of fun things that make them work better on GPU's
default data type of float 32
mor esuitable for deep learning than a numpy array

In [2]:
import torch
import numpy as np

Lists:

In [3]:
my_list = [1,2,3,4,5],[6,7,8,9]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9])

Numpy Arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.43641994, 0.60162358, 0.15871265, 0.01844502],
       [0.84565478, 0.58934062, 0.36110012, 0.37701558],
       [0.6048702 , 0.19706501, 0.40961721, 0.49160497]])

In [5]:
np1.dtype

dtype('float64')

Tensors

In [12]:
tensor_2d = torch.randn(3,5)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.0162,  1.4296,  0.1500, -1.7718, -1.6078],
        [-0.0658,  0.2793, -1.7085,  0.0489,  0.4427],
        [-0.5983,  1.3009,  0.4147,  0.3816,  0.2901]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4364, 0.6016, 0.1587, 0.0184],
        [0.8457, 0.5893, 0.3611, 0.3770],
        [0.6049, 0.1971, 0.4096, 0.4916]], dtype=torch.float64)