<a href="https://colab.research.google.com/github/Nramyanaga/Pytorch-Learning/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Math Operations
- Add, subtractm dividie, remainders, exponents,
-shorthand, and longhand
-reassignment

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# The items in each tensor is added together respective to its index
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition longhand, using existing function
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
# You can also store the tensor you added in a variable
tensor_add = tensor_a + tensor_b
tensor_add

tensor([ 6,  8, 10, 12])

In [9]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [10]:
# Subtraction function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [11]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
# Multiplication function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
# Division, converts to a float
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponents, puts a ^ b
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [18]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
# Reassignmengt shorthand
# tensor_a = tensor_a + tensor_b


# Longhand, that underscore only works when its an actual variable
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [21]:
tensor_a

tensor([11, 14, 17, 20])